language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install software-properties-common
  - sudo apt-get install clang-3.3
  - sudo apt-get install -y -qq cmake libgtest-dev libcppunit-dev libgnutls28-dev libgcrypt11-dev libmysqlclient-dev libev-dev zlib1g-dev libbz2-dev pkg-config libpcre3-dev libfcgi-dev libmagickwand-dev librrd-dev libtbb-dev
  - mkdir ~/gtest && cd ~/gtest && cmake /usr/src/gtest -DBUILD_SHARED_LIBS=ON && make && sudo cp -vp libgtest*.so /usr/local/lib/ && sudo ldconfig && cd -
  - export CXX=/usr/bin/clang && export CC=/usr/bin/clang && cmake -DCMAKE_BUILD_TYPE=debug -DENABLE_{RRD,EXAMPLES,TESTS}=ON
script:
  - make
  - ./tests/x0-test
branches:
  only:
    - master
notifications:
  recipients:
    - trapni@gmail.com
  email:
    on_success: change
    on_failure: always

# some `before_script` thingies I had to disable due to some Travis-fu
#  - sudo apt-get update -qq
